#!/usr/bin/env bash
# regist-user-device.sh — register a user + device against a running ccmux backend
# and write credentials to .env.agent.
#
# Usage:
#   ./scripts/regist-user-device.sh
#
# Environment overrides:
#   CCMUX_API_URL   HTTP base URL of the backend  (default: http://localhost:8080)
#   TEST_EMAIL      Account email                 (default: dev@ccmux.local)
#   TEST_PASSWORD   Account password              (default: devpassword123)
#   DEVICE_NAME     Display name for this machine (default: hostname-dev)
#
# Examples:
#   # Local backend
#   ./scripts/regist-user-device.sh
#
#   # Remote backend
#   CCMUX_API_URL=http://100.116.137.95:8080 ./scripts/regist-user-device.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

API_URL="${CCMUX_API_URL:-http://localhost:8080}"
TEST_EMAIL="${TEST_EMAIL:-dev@ccmux.local}"
TEST_PASSWORD="${TEST_PASSWORD:-devpassword123}"
DEVICE_NAME="${DEVICE_NAME:-$(hostname)-dev}"
ENV_FILE="$REPO_ROOT/.env.agent"

# Derive the WebSocket URL from the HTTP URL (http→ws, https→wss).
WS_URL="${API_URL/http:\/\//ws://}"
WS_URL="${WS_URL/https:\/\//wss://}"

log() { echo "[regist] $*"; }
die() { echo "[regist] ERROR: $*" >&2; exit 1; }

# ─── wait for backend ──────────────────────────────────────────────────────────

log "waiting for backend at $API_URL …"
for i in $(seq 1 30); do
  # Any HTTP status means the backend is reachable; auth failures are expected here.
  HTTP_CODE=$(curl -sS -o /dev/null -w '%{http_code}' \
    -X POST "$API_URL/api/auth/login" \
    -H 'Content-Type: application/json' \
    -d '{"email":"__probe__","password":"__probe__"}' || true)
  if [ "$HTTP_CODE" != "000" ]; then
    log "backend is up"
    break
  fi
  if [ "$i" -eq 30 ]; then
    die "backend not reachable after 30 s — is it running?"
  fi
  sleep 1
done

# ─── register or login ─────────────────────────────────────────────────────────

log "registering user: $TEST_EMAIL"
AUTH_RESP=$(curl -sf -X POST "$API_URL/api/auth/register" \
  -H 'Content-Type: application/json' \
  -d "{\"email\":\"$TEST_EMAIL\",\"password\":\"$TEST_PASSWORD\"}" 2>/dev/null) || true

if [ -z "$AUTH_RESP" ]; then
  log "user may already exist — logging in …"
  AUTH_RESP=$(curl -sf -X POST "$API_URL/api/auth/login" \
    -H 'Content-Type: application/json' \
    -d "{\"email\":\"$TEST_EMAIL\",\"password\":\"$TEST_PASSWORD\"}")
fi

ACCESS_TOKEN=$(echo "$AUTH_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])")
[ -z "$ACCESS_TOKEN" ] && die "could not obtain access token"
log "authenticated"

# ─── register device ───────────────────────────────────────────────────────────

log "registering device: $DEVICE_NAME"
DEVICE_RESP=$(curl -sf -X POST "$API_URL/api/devices" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H 'Content-Type: application/json' \
  -d "{\"name\":\"$DEVICE_NAME\",\"platform\":\"macos\"}")

DEVICE_ID=$(echo    "$DEVICE_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['device_id'])")
DEVICE_TOKEN=$(echo "$DEVICE_RESP" | python3 -c "import sys,json; print(json.load(sys.stdin)['device_token'])")
[ -z "$DEVICE_ID" ]    && die "could not obtain device_id"
[ -z "$DEVICE_TOKEN" ] && die "could not obtain device_token"
log "device registered: $DEVICE_ID"

# ─── write .env.agent ──────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Generated by scripts/regist-user-device.sh — do NOT commit
# Account: $TEST_EMAIL
export CCMUX_SERVER_URL="$WS_URL"
export CCMUX_DEVICE_ID="$DEVICE_ID"
export CCMUX_DEVICE_TOKEN="$DEVICE_TOKEN"
export CCMUX_IPC_SOCKET="/tmp/ccmux.sock"
EOF

log "credentials written to $ENV_FILE"
echo ""
echo "────────────────────────────────────────────────────────────"
echo "  Registered!"
echo ""
echo "  Backend:  $API_URL"
echo "  Device:   $DEVICE_ID"
echo "  File:     $ENV_FILE"
echo "────────────────────────────────────────────────────────────"
